# -*- coding: utf-8 -*-
"""Milestone 1B — Transformer Fake News Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5OYwkGGazO8eX3o64pwU6V8M1JAvs8Z

# Milestone 1B — Transformer Fake News Classifier
### Full Training + Ablation + Error Analysis
"""

!git clone https://github.com/remas565/Data-and-Task-Design-Brief-AI4203-Mini-Project-1.git
import os
os.chdir("Data-and-Task-Design-Brief-AI4203-Mini-Project-1/milestone1B")

# Imports
import config
import math, re, random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
import kagglehub
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, ConfusionMatrixDisplay)
from torch.utils.data import Dataset, DataLoader

# Reproducibility (important so results stay same)
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

print("Training Config\n")
print("D_MODEL:",    config.D_MODEL)
print("NUM_HEADS:",  config.NUM_HEADS)
print("DROPOUT:",    config.DROPOUT)
print("BATCH_SIZE:", config.BATCH_SIZE)
print("EPOCHS:",     config.EPOCHS)
print("LR:",         config.LR)
print("DEVICE:",     config.DEVICE)

"""### Model Architecture (Transformer Encoder from scratch)

"""

# Scaled Dot-Product Attention
# this is the core of attention (QK^T / sqrt(dk) → softmax → V)
class ScaledDotProductAttention(nn.Module):
    def __init__(self, d_k):
        super().__init__()
        self.d_k = d_k

    def forward(self, Q, K, V, mask=None):
        # Q, K, V = [batch, heads, seq_len, d_k]

        scores = torch.matmul(Q, K.transpose(-2, -1))
        # scores = [batch, heads, seq_len, seq_len]

        scores = scores / math.sqrt(self.d_k)

        if mask is not None:
            scores = scores.masked_fill(mask == 0, -1e9)

        attn_weights = torch.softmax(scores, dim=-1)
        # attn_weights = [batch, heads, seq_len, seq_len]

        output = torch.matmul(attn_weights, V)
        # output = [batch, heads, seq_len, d_k]

        return output, attn_weights

# Multi-Head Attention
# splits into multiple heads → each learns different relations
class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()

        assert d_model % num_heads == 0

        self.d_model = d_model
        self.num_heads = num_heads
        self.d_k = d_model // num_heads

        self.W_Q = nn.Linear(d_model, d_model)
        self.W_K = nn.Linear(d_model, d_model)
        self.W_V = nn.Linear(d_model, d_model)

        self.W_O = nn.Linear(d_model, d_model)

        self.attention = ScaledDotProductAttention(self.d_k)

    def forward(self, x, mask=None):
        # x = [batch, seq_len, d_model]

        batch_size = x.size(0)
        seq_len = x.size(1)

        # Linear projections
        Q = self.W_Q(x)
        K = self.W_K(x)
        V = self.W_V(x)
        # Q, K, V = [batch, seq_len, d_model]

        # Split heads
        Q = Q.view(batch_size, seq_len, self.num_heads, self.d_k)
        K = K.view(batch_size, seq_len, self.num_heads, self.d_k)
        V = V.view(batch_size, seq_len, self.num_heads, self.d_k)
        # [batch, seq_len, heads, d_k]

        # Transpose
        Q = Q.transpose(1, 2)
        K = K.transpose(1, 2)
        V = V.transpose(1, 2)
        # [batch, heads, seq_len, d_k]

        # Attention
        attn_output, attn_weights = self.attention(Q, K, V, mask)

        # Transpose back
        attn_output = attn_output.transpose(1, 2)
        # [batch, seq_len, heads, d_k]

        # Concatenate heads
        attn_output = attn_output.contiguous().view(batch_size, seq_len, self.d_model)
        # [batch, seq_len, d_model]

        output = self.W_O(attn_output)
        # [batch, seq_len, d_model]

        return output

# Transformer Encoder Block
# (MHA + FFN) with residual connections + layer norm
class TransformerEncoderBlock(nn.Module):
    def __init__(self, d_model, num_heads, d_ff, dropout=0.1):
        super().__init__()

        # 1. Multi-Head Attention layer
        self.mha = MultiHeadAttention(d_model, num_heads)

        # 2. Feed Forward Network (FFN)
        # Expands to d_ff, applies ReLU, then compresses back to d_model
        self.ffn = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(d_ff, d_model)
        )

        # 3. Normalization & Dropout layers
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        # Input x shape: [batch_size, seq_len, d_model]


        # Block 1: Self-Attention


        attn_output = self.mha(x, mask)
        # attn_output shape: [batch_size, seq_len, d_model]


        # Block 2: Add & Norm 1 (Residual Connection)

        attn_output = self.dropout(attn_output)
        x = x + attn_output                     # Residual connection (Add)
        x = self.norm1(x)
        # x shape: [batch_size, seq_len, d_model]


        # Block 3: Feed Forward Network

        ffn_output = self.ffn(x)
        # ffn_output shape: [batch_size, seq_len, d_model]


        # Block 4: Add & Norm 2 (Residual Connection)

        ffn_output = self.dropout(ffn_output)
        x = x + ffn_output                      # Residual connection (Add)
        x = self.norm2(x)

        # Final output shape: [batch_size, seq_len, d_model]
        return x

# Positional Embedding (learned)
# gives the model sense of order (since attention itself is orderless)
class LearnedPositionalEmbedding(nn.Module):
    def __init__(self, max_len, d_model):
        super().__init__()
        self.pos_embedding = nn.Embedding(max_len, d_model)

    def forward(self, x):
        batch_size, seq_len = x.size()
        positions = torch.arange(0, seq_len, device=x.device).unsqueeze(0).expand(batch_size, seq_len)
        return self.pos_embedding(positions)

# Transformer Classifier
# embedding → encoder → mean pooling → classification
class TransformerClassifier(nn.Module):
    def __init__(self, vocab_size, d_model, num_heads, d_ff, num_classes, max_seq_len=100, dropout=0.1):
        super().__init__()

        self.d_model = d_model
        # 1. Embedding layers for tokens and their positions
        self.tok_embedding = nn.Embedding(vocab_size, d_model)
        self.pos_embedding_layer = LearnedPositionalEmbedding(max_seq_len, d_model)

        # 2. Main Transformer Encoder unit
        self.encoder_block = TransformerEncoderBlock(d_model, num_heads, d_ff, dropout)

        # 3. Final decision layer (Classification Head)
        self.fc_out = nn.Linear(d_model, num_classes)

        self.dropout = nn.Dropout(dropout)
        self.scale = math.sqrt(d_model) # Scaling factor per original paper

    def forward(self, x, mask=None):
        # Step 1: Compute scaled token and positional embeddings
        token_embeds = self.tok_embedding(x) * self.scale
        pos_embeds = self.pos_embedding_layer(x)

        # Step 2: Combine embeddings and pass through the encoder
        x = self.dropout(token_embeds + pos_embeds)
        x = self.encoder_block(x, mask)

        # Step 3: Pooling - Aggregate all word vectors into one sentence vector
        x = x.mean(dim=1)

        # Step 4: Final classification output
        return self.fc_out(x)

"""###Data Loading & Preprocessing

"""

path = kagglehub.dataset_download("saurabhshahane/fake-news-classification")
df   = pd.read_csv(os.path.join(path, "WELFake_Dataset.csv"))

print("BEFORE CLEANING:")
print(df[["title", "text", "label"]].head(5))

# clean + merge title and text
# remove noise like "Reuters — ..."

# cleaning function
def clean_news_text(text):
    text = str(text).strip()

    # remove source prefixes
    text = re.sub(r'^[A-Z][A-Z\s]{1,30}(?:,\s*[A-Za-z]+)?\s*\([^)]+\)\s*[-–]\s*', '', text)
    text = re.sub(r'^[A-Z]{2,}(?:\s+[A-Z]{2,})*(?:,\s*[A-Za-z]+)?\s*[-–]\s*', '', text)
    text = re.sub(r'^\((?:Reuters|AP|AFP|BBC|CNN|UPI)\)\s*[-–]?\s*', '', text, flags=re.IGNORECASE)

    return text.strip()


# apply cleaning
df["title_clean"] = df["title"].fillna("").apply(clean_news_text)
df["text_clean"]  = df["text"].fillna("").apply(clean_news_text)

# combine into one input
df["content"] = ("[TITLE] " + df["title_clean"] + " [SEP] " + df["text_clean"]).str.strip()

# normalize
df["content"] = df["content"].str.lower().str.replace(r"\s+", " ", regex=True)

# filtering
df = df.dropna(subset=["label"])
df = df[df["content"].str.len() > 10]
df = df.drop_duplicates(subset=["content"]).reset_index(drop=True)

df = df[["content", "label"]]
df["label"] = df["label"].astype(int)

print(f"\nTotal samples after cleaning: {len(df)}")
print(df["label"].value_counts())

# Split (Train / Validation / Test)
X_raw = df["content"].values
y     = df["label"].values

# 80 / 10 / 10 split
X_tr_raw, X_tmp_raw, y_tr, y_tmp = train_test_split(
    X_raw, y, test_size=0.2, random_state=SEED, stratify=y)

X_va_raw, X_te_raw, y_va, y_te = train_test_split(
    X_tmp_raw, y_tmp, test_size=0.5, random_state=SEED, stratify=y_tmp)

print(f"Train: {len(X_tr_raw)}  Val: {len(X_va_raw)}  Test: {len(X_te_raw)}")

# Vocabulary Building (from training data only)
# we only build vocab from TRAIN set to avoid data leakage

def tokenize(text):
    return str(text).lower().split()

counter = Counter()
for t in X_tr_raw:
    counter.update(tokenize(t))

# special tokens
vocab = {"<PAD>": 0, "<UNK>": 1}

# keep top words only
for word, _ in counter.most_common(config.MAX_VOCAB_SIZE - 2):
    vocab[word] = len(vocab)

VOCAB_SIZE = len(vocab)
print("Vocab size:", VOCAB_SIZE)

# Encoding (text → numbers)

def encode(text):
    ids = [vocab.get(t, vocab["<UNK>"]) for t in tokenize(text)]

    # cut if long
    ids = ids[:config.MAX_SEQ_LEN]

    # pad if short
    ids += [vocab["<PAD>"]] * (config.MAX_SEQ_LEN - len(ids))

    return ids

# apply encoding
X_tr = np.array([encode(t) for t in X_tr_raw])
X_va = np.array([encode(t) for t in X_va_raw])
X_te = np.array([encode(t) for t in X_te_raw])

# Dataset + DataLoader

class NewsDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.long)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, i):
        return self.X[i], self.y[i]


train_loader = DataLoader(NewsDataset(X_tr, y_tr), batch_size=config.BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(NewsDataset(X_va, y_va), batch_size=config.BATCH_SIZE, shuffle=False)
test_loader  = DataLoader(NewsDataset(X_te, y_te), batch_size=config.BATCH_SIZE, shuffle=False)

"""### Training & Evaluation Functions

"""

# Train (one epoch)
# this runs one full pass over training data

def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()

    total_loss = 0

    for X_batch, y_batch in loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        optimizer.zero_grad()

        # forward
        outputs = model(X_batch)

        loss = criterion(outputs, y_batch)

        # backward
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)

# Evaluate (validation / test)

def evaluate(model, loader, criterion, device):
    model.eval()

    total_loss = 0
    preds_all = []
    labels_all = []

    with torch.no_grad():
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            outputs = model(X_batch)

            total_loss += criterion(outputs, y_batch).item()

            preds = outputs.argmax(1)

            preds_all.extend(preds.cpu().numpy())
            labels_all.extend(y_batch.cpu().numpy())

    avg_loss = total_loss / len(loader)
    acc = accuracy_score(labels_all, preds_all)

    return avg_loss, acc, np.array(preds_all), np.array(labels_all)

# Full Experiment Runner

def run_experiment(dropout, tag, epochs=config.EPOCHS):

    torch.manual_seed(SEED)

    # build model
    model = TransformerClassifier(
        vocab_size=VOCAB_SIZE,
        d_model=config.D_MODEL,
        num_heads=config.NUM_HEADS,
        d_ff=config.D_FF,
        num_classes=config.NUM_CLASSES,
        max_seq_len=config.MAX_SEQ_LEN,
        dropout=dropout
    ).to(config.DEVICE)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=config.LR)

    history = {
        "train_loss": [],
        "val_loss": [],
        "val_acc": []
    }

    print(f"\n{'='*55}")
    print(f"  Experiment : {tag}")
    print(f"  dropout={dropout} | epochs={epochs} | lr={config.LR}")
    print(f"  batch={config.BATCH_SIZE} | max_seq_len={config.MAX_SEQ_LEN}")
    print(f"  d_model={config.D_MODEL} | d_ff={config.D_FF} | heads={config.NUM_HEADS}")
    print(f"{'='*55}")

    # Training loop
    for epoch in range(1, epochs + 1):

        train_loss = train_one_epoch(model, train_loader, criterion, optimizer, config.DEVICE)

        val_loss, val_acc, _, _ = evaluate(model, val_loader, criterion, config.DEVICE)

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        print(f"Epoch {epoch}/{epochs} | "
              f"Train Loss: {train_loss:.4f} | "
              f"Val Loss: {val_loss:.4f} | "
              f"Val Acc: {val_acc:.4f}")

    # Final test evaluation
    _, test_acc, test_preds, test_labels = evaluate(model, test_loader, criterion, config.DEVICE)

    print(f"\nFinal Test Accuracy: {test_acc:.4f} ({test_acc*100:.2f}%)")

    print("\nClassification Report:")
    print(classification_report(test_labels, test_preds,
                                target_names=["Fake (0)", "Real (1)"]))

    return model, history, test_acc, test_preds, test_labels

"""## PART A — Full Training: Baseline
###(dropout=0.1)


"""

print("PART A — Full Training & Evaluation")

model_base, hist_base, acc_base, preds_base, labels_base = run_experiment(
    dropout=0.1,
    tag="Baseline (dropout=0.1)"
)


# Plot Baseline Curves

epochs_range = range(1, config.EPOCHS + 1)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# loss
axes[0].plot(epochs_range, hist_base["train_loss"], marker='o', label="Train")
axes[0].plot(epochs_range, hist_base["val_loss"], marker='s', label="Val")
axes[0].set_title("Loss Curve")
axes[0].legend()
axes[0].grid(True)

# accuracy
axes[1].plot(epochs_range, hist_base["val_acc"], marker='^')
axes[1].set_title("Validation Accuracy")
axes[1].set_ylim(0, 1)
axes[1].grid(True)

plt.tight_layout()
plt.savefig("baseline_curves.png", dpi=150)
plt.show()

"""## PART B — Ablation  
###Dropout 0.1 vs 0.3

"""

print("PART B — Ablation")

model_abl, hist_abl, acc_abl, preds_abl, labels_abl = run_experiment(
    dropout=0.3, tag="Ablation (dropout=0.3)"
)

# Compare Curves
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

axes[0].plot(epochs_range, hist_base["val_loss"], marker='o', label="Baseline (dropout=0.1)")
axes[0].plot(epochs_range, hist_abl["val_loss"],  marker='s', label="Ablation (dropout=0.3)")
axes[0].set_title("Ablation — Validation Loss")
axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Loss")
axes[0].legend(); axes[0].grid(True)

axes[1].plot(epochs_range, hist_base["val_acc"], marker='o', label="Baseline (dropout=0.1)")
axes[1].plot(epochs_range, hist_abl["val_acc"],  marker='s', label="Ablation (dropout=0.3)")
axes[1].set_title("Ablation — Validation Accuracy")
axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("Accuracy")
axes[1].set_ylim(0, 1); axes[1].legend(); axes[1].grid(True)

plt.suptitle("Part B — Ablation Study: Dropout = 0.1 vs 0.3", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig("ablation_curves.png", dpi=150)
plt.show()

# Results Table
print("\n" + "="*60)
print("  PART B — ABLATION RESULTS TABLE")
print("="*60)
print(f"  {'Setting':<35} {'Test Accuracy':>12}")
print("-"*60)
print(f"  {'Baseline  (dropout=0.1)':<35} {acc_base:>11.4f}")
print(f"  {'Ablation  (dropout=0.3)':<35} {acc_abl:>11.4f}")
print("="*60)

"""## PART C — Error Analysis
###Confusion Matrix

"""

print("PART C — Error Analysis (Confusion Matrix)")

cm = confusion_matrix(labels_base, preds_base)

fig, ax = plt.subplots(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                               display_labels=["Fake (0)", "Real (1)"])
disp.plot(ax=ax, colorbar=True, cmap="Blues")
ax.set_title("Confusion Matrix — Baseline Model (Test Set)", fontweight='bold')
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=150)
plt.show()

# ── Confusion matrix numbers ──────────────────
tn, fp, fn, tp = cm.ravel()
print(f"\n  True Negatives  (Fake correctly classified): {tn}")
print(f"  False Positives (Fake misclassified as Real): {fp}")
print(f"  False Negatives (Real misclassified as Fake): {fn}")
print(f"  True Positives  (Real correctly classified):  {tp}")

total      = tn + fp + fn + tp
fp_rate    = fp / (tn + fp) * 100
fn_rate    = fn / (tp + fn) * 100

print(f"\n  False Positive Rate: {fp_rate:.2f}%  "
      f"(fake news passed as real)")
print(f"  False Negative Rate: {fn_rate:.2f}%  "
      f"(real news blocked as fake)")

"""Observations:

1. The confusion matrix shows strong diagonal values, which means the model correctly classifies most fake and real news samples and performs well overall.


---


2. The model makes more false positives (165 fake predicted as real), which suggests that some fake news articles closely resemble real news in structure and writing style, making them harder to detect.


---


3. The false negatives (133 real predicted as fake) indicate that some real news articles contain strong or sensational language, which overlaps with patterns commonly found in fake news, leading to misclassification.

## PART D — Responsible AI Mini-Note

**Dataset:**
Fake News Classification (Kaggle)
https://www.kaggle.com/datasets/saurabhshahane/fake-news-classification?resource=download

**Dataset Source & Intended Use:**

The WELFake dataset *(Kaggle)* combines multiple public news datasets and contains labelled fake and real news articles. It is mainly used for academic research in fake-news detection using NLP and machine learning models.

---
**Limitation / Risk:**

It has temporal and political bias, meaning most articles come from around 2015–2018 and focus mainly on English US political news (especially around the 2016 election period). This makes the dataset not fully representative of other topics, countries, or newer time periods, which limits generalisation.



---

**Impact:**

The model may fail on other domains, languages, or newer misinformation styles, leading to incorrect predictions.


---


**Mitigation:**

Train the model on more diverse and multilingual datasets and include human review in real-world use.
"""